### ISSUE TITLE
TypeError: d3 is undefined

### ISSUE THREAD

**Issue by bertocast** [metricsgraphics/metrics-graphics#639]
Hi folks,

I'm trying to use the library with meteor and I getting `TypeError: d3 is undefined` on the client console.

This my _list.js_

```
import './list.html';

if (Meteor.isClient) {
    Template.graphsList.rendered = function () {
        MG.data_graphic({
            title: "Downloads",
            description: "This graphic shows a time-series of downloads.",
            data: [{'date': new Date('2014-11-01'), 'value': 12},
                {'date': new Date('2014-11-02'), 'value': 18}],
            width: 600,
            height: 250,
            target: '#downloads',
            x_accessor: 'date',
            y_accessor: 'value'
        })
    };
}
```

And this is my _list.html_

```
<template name="graphsList">
    <div class="box">
        <svg id="downloads" class="graphic"></svg>
    </div>
</template>
```

It's one of the simplest examples I've found, but I'm not able to make it work.
I have installed the metricsgraphics meteor package, aswell as d3 and jquery.
What am I doing wrong?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by recog-arch** [comment]
Yes, sorry!

**Comment by bertocast** [comment]
Yes, sorry!
