### ISSUE TITLE
min_x=0 doesn't work

### ISSUE THREAD

**Issue by philz** [metricsgraphics/metrics-graphics#729]
As visible in the screenshots below (which are just the interactive demo), setting "min_x: 0" doesn't make the x-axis start at value 0.  Rather, it behaves as if min_x is set to its default, null, and doesn't do anything.

I suspect the bug is here, where min_x is being used in a truthiness context.

`  if (mx.min === mx.max && !(args.min_x && args.max_x)) {
`

min_x: 1 looks like this:
![image](https://cloud.githubusercontent.com/assets/60228/21069220/a7297564-be2c-11e6-982c-4d158150d324.png)

min_x: 0 should be very similar, but isn't:

![image](https://cloud.githubusercontent.com/assets/60228/21069221/ac71721a-be2c-11e6-954c-3b5f95a09167.png)

**Comment by StompyNZ** [comment]
it's probably this line from the process_line function: 

var from = (args.min_x) ? args.min_x : start_date;

if args.min_x is 0 then (args.min_x) is false, so its using start_date instead of 0

the test should be:
var from = (args.min_x != null) ? args.min_x : start_date;
