### ISSUE TITLE
How to sort bar chart colums?

### ISSUE THREAD

**Issue by brylie** [metricsgraphics/metrics-graphics#734]
How can I specify the sort order for bar chart columns? E.g. I have a nominal variable with the values 'low', 'medium', and 'high' that should appear in the chart in a familiar order.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by brylie** [comment]
We're no longer using Metrics Graphics, although I do appreciate the spirit of the project.
