### ISSUE TITLE
Rollover sometimes overlaps markers, making them both unreadable

### ISSUE THREAD

**Issue by openjck** [metricsgraphics/metrics-graphics#839]
## Steps to reproduce

Load [this JSFiddle](https://jsfiddle.net/jrp7fdkk/1/)

## Actual result

![](https://user-images.githubusercontent.com/933396/37804497-ea59b430-2e0a-11e8-876a-db59f10e1584.png)

**Comment by openjck** [comment]
This would probably look fine if the tooltip had a solid white background and some padding.

**Comment by hamilton** [comment]
This is a rollover, not a tooltip. But yes I agree we need to refine how we calculate the position w/ markers - I've had this problem as well. My feeling would be to make a larger buffer between the header content & the graph body so there is never really any chance they'll collide.

**Comment by openjck** [comment]
I was able to work around this on [mozilla/ensemble](https://github.com/mozilla/ensemble) by just moving the rollover box up 50 pixels. That works well for our use case, but I'm not sure if 50px is exactly the right amount for all possible configurations. If it is, I can submit a quick PR that does that.

**Comment by wlach** [comment]
Could you try making the change and see how the examples render when running `gulp serve`? I'm not sure if this is a case where we can just tweak the default or if we need to devise a more intelligent heuristic.
