### ISSUE TITLE
Is jQuery needed for tooltips?

### ISSUE THREAD

**Issue by openjck** [metricsgraphics/metrics-graphics#842]
The README [mentions](https://github.com/metricsgraphics/metrics-graphics#dependencies) that jQuery is needed to enable tooltips. Is that still accurate? I'm using tooltips currently without jQuery being present.

**Comment by wlach** [comment]
jquery is definitely still needed for chart labels and buttons, but am not sure about tooltips. We have plans to exorcise the jquery dependency completely at some point, hopefully within the next few months.

**Comment by openjck** [comment]
Awesome! Can you link me to an example of chart labels and buttons? I'm not sure what that refers to.

**Comment by mvolkmann** [comment]
Can someone show a correct way to include jquery in an app that uses metrics-graphics?
Do I have to make sure it is included AFTER metrics-graphics?
I'm trying to use this in a React app. Can I include it with a script tag in index.html?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by openjck** [comment]
Yes, this can be closed. My support question was answered. Thanks!
