### ISSUE TITLE
Labels display rounded numbers rather than decimals

### ISSUE THREAD

**Issue by sarah-clements** [metricsgraphics/metrics-graphics#844]
Despite the value being a number with two decimals, the labels are shown with one decimal. If the value of 1.00 is changed to 2.00 in the [fiddle](https://jsfiddle.net/n5u2wwjg/8067/), all labels then display numbers that have been rounded to a whole number.

[Here](https://jsfiddle.net/n5u2wwjg/8064/) is another example where they've been completely rounded.

**Comment by hamilton** [comment]
Yes, this is intended behavior. Typically when the range of numbers is larger, the display of decimals is irrelevant. The point of the axis is to provide some grounding on the general range of values of a number. When the numbers are smaller, decimal values make more sense, because you often need a finer-grained axis.

**Comment by sarah-clements** [comment]
Sure, that makes sense, but I was referring to the labels of data points on the graph. In this [example](https://jsfiddle.net/n5u2wwjg/9788/) the values 0.29 and 0.27 both display as "0.3" and 0.49 displays as "0.0" on the labels, so it doesn't really align with how it's visually displayed on the graph. Would you consider adding an option to customize the hover label format?

**Comment by hamilton** [comment]
Ah, I understand the issue now - thanks for clarifying. There seems to have been a bug introduced somewhere down the line.

For now, you can use the `y_mouseover` argument:

```javascript
MG.data_graphic({
  title: "Line Chart",
  data: sampleData,
  width: 500,
   y_mouseover: d=>d3.format('.2f')(d.value),
   interpolate: d3.curveLinear,
   target: '#target',
   x_accessor: 'date',
   y_accessor: 'value'
});
```

We'll investigate why `decimals` doesn't appear to be working properly in this fiddle example.

**Comment by wlach** [comment]
I will look into why the decimals option isn't working now.
