### ISSUE TITLE
Some data causes x-axis to show year multiple times

### ISSUE THREAD

**Issue by openjck** [metricsgraphics/metrics-graphics#848]
## Steps to reproduce

Load [this JSFiddle](https://jsfiddle.net/jrp7fdkk/11/), which renders the following data:

```javascript
[
    { x: new Date('2017-01-01'), y: 0 },
    { x: new Date('2019-01-01'), y: 10 },
]
```

## Actual result

![](https://user-images.githubusercontent.com/933396/38705003-1dcc1e54-3e76-11e8-9945-a58b450839ec.png)

**Comment by wlach** [comment]
Temporary workaround might be to use `xax_count` to reduce the number of ticks. Looking into a better solution right now...
