### ISSUE TITLE
Set user-select: none on SVG elements

### ISSUE THREAD

**Issue by openjck** [metricsgraphics/metrics-graphics#852]
This was found by [one of our testers](https://github.com/mozilla/ensemble/issues/130).

Basically, when using Firefox for Android, tapping on a data point causes the *Select* context menu to appear. This doesn't happen when `user-select: none` is applied to the SVG element. You may want to use vendor prefixes for that rule depending on which browser you support.

![](https://user-images.githubusercontent.com/1583842/39059227-96a55344-44c6-11e8-852b-9c504e519562.png)

**Comment by wlach** [comment]
@cnwangjie I know you set the user-select property to none in this commit to add brushing/zooming:

https://github.com/metricsgraphics/metrics-graphics/commit/c4c0ac9a4d66b31088b3e7fc83a489b33ce3d7dc

Do you have any thoughts on how to solve this?

**Comment by cnwangjie** [comment]
@wlach I've confirmed this problem.
As @openjck said. We just add css similar to the following can avoid this problem for the line chart in Firefox for Android.
```css
.mg-rollover-rect * {
    user-select: none;
    -moz-user-select: none;
}
```
I would like to submit a PR for this and avoid this problem for all types of charts.
