### ISSUE TITLE
Brushing & zooming should persist when zooming over an overflow plot

### ISSUE THREAD

**Issue by wlach** [metricsgraphics/metrics-graphics#855]
@cnwangjie recently added brushing and zooming support in #851, including support for an "overview plot" which you can use to quickly brush/zoom in on a subplot. This works great, however currently the selection over the overview plot disappears after the zoom happens. It would be great if it operated similar to how flot does, where the selection over the overview plot persisted:

![image](https://user-images.githubusercontent.com/20569/40510013-4db0b2e2-5f69-11e8-9fb5-08f73752f0c0.png)
http://www.flotcharts.org/flot/examples/zooming/index.html

@cnwangjie -- do you have any ideas on how difficult this would be?

**Comment by cnwangjie** [comment]
@wlach Did you mean that when we zoom the original chart, create a corresponding extent in the overview plot? I submitted a PR (#857) to achieve this. Is this what you expected?
