### ISSUE TITLE
Optional callback when zooming

### ISSUE THREAD

**Issue by wlach** [metricsgraphics/metrics-graphics#866]
To enable us to persist the zooming level in a URL as seen here:

https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-inbound,1640626,1,1&zoom=1527860804962.76,1527908121265.0603,211.1940298507463,296.2686567164179

We should allow persisting the zoom level after the selection succeeds.

**Comment by cnwangjie** [comment]
I've submitted a PR for this (#867). I think currently we only need a trigger for a brushing event. The user can use `processed.zoom_x / processed.zoom_y` to get the actual zoomed data range. If we need to allow user to change brushing behavior I can make more changes.

**Comment by wlach** [comment]
@cnwangjie is there currently a way to set the zoom level when constructing the graph? That is also an important feature.

**Comment by cnwangjie** [comment]
It is possible to use the exported `MG.zoom_to_data_domain` and `MG.zoom_to_data_range` functions to control the zoom level. Just need to call it after `MG.data_graphic` can achieve the effect of setting the initial zoom level.

**Comment by wlach** [comment]
Ok, those should be good for now! See my comment on the PR for some requested changes.
