### ISSUE TITLE
Update to d3 v5

### ISSUE THREAD

**Issue by edmorley** [metricsgraphics/metrics-graphics#871]
d3 v5.0.0 was released in January:
https://github.com/d3/d3/releases

It would be great to get metrics-graphics using the latest version, if only to avoid breakage by accidentally upgrading direct `d3` dependencies to v5 when needing to mix and match lower and higher level APIs.

**Comment by wlach** [comment]
This is done now through renovate, though unreleased. I will probably be releasing a new major version of metricsgraphics with these changes at the end of the summer.

**Comment by edmorley** [comment]
Awesome :-)

**Comment by mattwilson1024** [comment]
Did a new version ever get released? I have some issues at the moment because metrics-graphics depends on d3 v4, but other areas of our app depend on d3 v5. Wonder if there's a recommended solution for this?

**Comment by wlach** [comment]
@mattwilson1024 not yet, I'm in the middle of a refactoring of the codebase before the next major release. I may wind up releasing a work-in-progress on npm soonish, keep your eyes on #907.
