### ISSUE TITLE
Add documentation that index is a reserved property on data objects

### ISSUE THREAD

**Issue by thegrandpoobah** [metricsgraphics/metrics-graphics#896]
I upgraded from MG 2.10.x to 2.16.x recently and the rollovers on my graphs stopped working in any meaningful way. It ended up being because of [this commit](https://github.com/metricsgraphics/metrics-graphics/commit/378e01290dc73252f643981d806ded268da6d60b) which adds a property onto the data series passed to mg called `index` which was the property that I was using myself for the the `y_accessor`.

Ideally, the data being passed in by the user isn't being manipulated by the library, but more realistically, maybe some documentation that `index` is a reserved property name on data objects?

**Comment by wlach** [comment]
Yeah this isn't optimal, I think we should try to not manipulate the data passed in by the user somehow. If fixing this is really hard, we should at the least use some kind of object key which is likely to be unique, like `__index__`, as a stopgap.
