### ISSUE TITLE
Reduce impact of metrics-graphics on bundle size

### ISSUE THREAD

**Issue by edmorley** [metricsgraphics/metrics-graphics#903]
Hi :-)

The README currently says:

> MetricsGraphics.js is a library optimized for visualizing and laying out time-series data. At under 80KB (minified), ...

However it actually causes a **385KB** (minified) increase in bundle size:
https://bundlephobia.com/result?p=metrics-graphics@2.15.6

This is larger than [react](https://bundlephobia.com/result?p=react@16.5.0)+[react-dom](https://bundlephobia.com/result?p=react-dom@16.5.0) (96KB), [jQuery](https://bundlephobia.com/result?p=jquery@3.3.1) (85KB), [lodash](https://bundlephobia.com/result?p=lodash@4.17.10) (69KB), [bootstrap](https://bundlephobia.com/result?p=bootstrap@4.1.3) (49KB) and [flot](https://bundlephobia.com/result?p=flot@0.8.0-alpha) (32KB)
...all added together! (And I don't think this is even including the CSS)

Whilst 70% of the 385KB comes from the dependencies of metrics-graphics - the weight they add can't just be written off when discussing its size, since it's the way that metrics-graphics is structured/bundled that causes all of them to be included even if they are not used.

It's also worth noting that d3 got quite a bit larger in v5 (compare [v4](https://bundlephobia.com/result?p=d3@4.12.2) and [v5](https://bundlephobia.com/result?p=d3@5.7.0)) which is not included in the above (since the v5 upgrade is only on `master`) - so the issue is going to be even worse in the next release / over time as the d3 package ecosystem gets larger.

Things that would likely help with this:
* Using ES6 imports/exports and not globals (part of #811)
* Switching to rollup (#902)
* Depending on/importing the individual d3 packages rather than the overall `d3` package (eg #662 / #667)
* Making both a CJS and an ES6 modules version of the package available (the former under `main` in package.json, the latter under `module`)
* Seeing if `"sideEffects": "false"` can be used for improved tree shakability: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by jens-ox** [comment]
Hi! Please see #929 -- the new version comes at ~10kB minified and gzipped.
