### ISSUE TITLE
brushing/zooming sometimes results in graph completely collapsing 

### ISSUE THREAD

**Issue by thorsteinssonh** [metricsgraphics/metrics-graphics#904]
Our metrics graphs sometimes completely collapse when resetting zoom/brushing.

Here is an example graph, http://docs.seamon.io/embed/sample1.html

An here is what sometimes happens when zooming our (resetting the graph)
with a single click, see uploaded screenshot here:
[http://pasteall.org/pic/show.php?id=14253a211247fd23494aa92608894c05](http://pasteall.org/pic/show.php?id=14253a211247fd23494aa92608894c05)

This collapse happens on both Firefox and Chrome.
Seems to happen especially if single click few time in short succession.

**Comment by cnwangjie** [comment]
It is caused by selecting a too small range, I've submitted a PR (#905) to avoid collapsing in this case. 

Before a new version fixed this problem is published you can use the callback function `brushing_selection_changed` to achieve similar effect.

```js
brush: 'x',
brushing_selection_changed(args, range) {
if (range.x[0] === range.x[1]) MG.zoom_to_raw_range(args)
},
```

**Comment by thorsteinssonh** [comment]
excellent thank you!
I think we can close this one.

**Comment by wlach** [comment]
Thanks!
