### ISSUE TITLE
Uncaught TypeError: areas.transition is not a function

### ISSUE THREAD

**Issue by anish9461** [metricsgraphics/metrics-graphics#928]
I am getting the 'Uncaught TypeError: areas.transition is not a function" with I try the brush: "xy" option in the MG.data_graphic. I am trying this on React.

**Comment by jtleniger** [comment]
I'm also experiencing this issue. I looked through https://github.com/d3/d3-selection/issues/185 but have been unable to resolve this.

**Comment by jens-ox** [comment]
The `MG.data_graphic` API is obsolete. Closing this.
