### ISSUE TITLE
How to include and use metrics-graphics in html without npm?

### ISSUE THREAD

**Issue by sm4rtk1dz** [metricsgraphics/metrics-graphics#937]
Hi everyone!

I want to use this library in a project that runs on PHP, i'd like to add the metrics-graphics js as a bundle included in the html output of the PHP code, is there any way to do this? if so, how do I do it? I've been looking but couldn't find any docs on the topic.

Thank you!

**Comment by jasco** [comment]
From your question, I'm guessing you might be interested in including the library using a script tag in your HTML file from a CDN such as https://cdnjs.com/libraries/metrics-graphics.  Am I misunderstanding your needs?

**Comment by sm4rtk1dz** [comment]
Yes! that's exactly what I need :)

**Comment by jens-ox** [comment]
Hi @sm4rtk1dz! Thanks for checking out metrics-graphics. I just published the first beta of v3 - if you want to use it, you can download a pre-built version from the [releases page](https://github.com/metricsgraphics/metrics-graphics/releases/tag/v3.0.0-beta1.0) :relaxed:

**Comment by jens-ox** [comment]
Also, using artifacts from the releases page is the way I'd go when loading it directly via npm is not an option.
