### ISSUE TITLE
Can't color bar charts?

### ISSUE THREAD

**Issue by jberryman** [metricsgraphics/metrics-graphics#944]
I've tried `colors: [ list of colors... ]` and it seems to have no effect.

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) or [Github Discussions](https://docs.github.com/en/discussions) (if one is setup for this repo) is better than Github.

I'd suggest closing this one.

**Comment by jberryman** [comment]
> Is this an issue with the code itself, or a general question?

the library has almost no documentation I can find, so there's no way to distinguish the two. I can't recall what I was trying to do here, but don't use this library
